### ISSUE TITLE
Feature request: support the Closure Compiler in advanced mode

### ISSUE THREAD

**Issue by trkjgrdg** [petkaantonov/bluebird#1024]
Could Bluebird support the Closure Compiler in advanced mode?  (Or if it already does, that should be documented.)

As far as I can tell, the Closure Compiler in advanced mode is the only minifier that does non-trivial property renaming, and is widely agreed to be best minifier if one can follow the restrictions it imposes.

I had a brief glance at the code, and the usual stumbling block of mixing dot and bracket accessors seems to be mostly non-existent.  On the other hand, I imagine that code generation would be problematic.  Could it perhaps be disabled with a flag?

**Comment by benjamingr** [comment]
@trkjgrdg would you be interested in working towards making bluebird run through the closure compiler in advanced mode?

Code generation is crucial for performance but is turned off in client side code by default - so that should not be a problem if the goal is to deliever a version minified with the closure compiler.

**Comment by trkjgrdg** [comment]
@benjamingr yes.  I will let you know how it goes.

**Comment by petkaantonov** [comment]
It will require a complete rewrite that I'm pretty sure will not even work out in the end, so no. If you are able to do it without regression to features and perf, you are welcome to open a PR.
