### ISSUE TITLE
Warnings about Promise not being returned

### ISSUE THREAD

**Issue by ORESoftware** [petkaantonov/bluebird#1054]
I was told by Petka that the warnings here

https://github.com/sequelize/sequelize/issues/5650

were not being issued by Bluebird code, but somehow I find that hard to believe. It must be internal to Bluebird. Perhaps Sequelize is using an older version of Bluebird?

I do understand that the warning has its place, but not sure if I need to see it as it's filling up my logs, thanks

**Comment by ben-page** [comment]
The warnings are being issued by Bluebird. Bluebird is warning you about a runaway promise. But, they are not caused by Bluebird. The cause is either sequelize or your code. Check out the docs, if you haven't already. [Warning Explanations](http://bluebirdjs.com/docs/warning-explanations.html) You can easily disable or suppress this warning, but the majority of the time this warning is an indication of a problem.

A runaway promise is a promise that not attached to the promise chain that it was created in. If a runaway promise rejects, it doesn't cause the whole promise chain to reject. And that will lead to the rejection being swallowed or an UnhandledRejection error crashing you application.

Most of the time you just want to attach the runaway promise to the outer promise chain. There are a few cases where you may want to suppress the warning, such as if you are completely recovering from the error or you are emitting the error event.

I suggest you do not just disable the warnings. That take the time to identify the source of the runaway promise. It's likely very to cause your application crash and it's often easy to fix (just return the inner promise).

**Comment by petkaantonov** [comment]
The warning has been improved in 3.4.3
