### ISSUE TITLE
Illegal invocation error with navigator.geolocation.getCurrentLocation

### ISSUE THREAD

**Issue by vincaslt** [petkaantonov/bluebird#1179]
1) What version of bluebird is the issue happening on?
3.4.1

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Opera 38

3) Did this issue happen with earlier version of bluebird?
Don't know, but some clues I've found by googling do indicate that people managed to run the same code I am trying to run.

Here is the simplest code example to test the issue: https://jsfiddle.net/akdog4r0/
Or the code here: 
```
var getLocation = Promise.promisify(navigator.geolocation.getCurrentPosition);

getLocation().then(function(pos) {
	console.log(pos);
}).catch(function(err) {
	console.log(err);
});
```

Running this code throws `TypeError: Illegal invocation` and points to the getLocation() call. This happened also on some local app, js fiddle is just to illustrate the problem.

**Comment by bergus** [comment]
Have a look at https://stackoverflow.com/questions/31639639/cant-apply-lodash-partial-to-function-created-with-bluebird-promisifyall, https://stackoverflow.com/questions/38577330/cannot-read-property-of-undefined-after-promise-promisify, https://stackoverflow.com/questions/32509904/how-to-ensure-correct-this-with-promise-promisify and many others :-)

**Comment by vincaslt** [comment]
Maybe I don't understand the problem clearly, but nothing that I've gathered from those articles have helped me to solve the problem...

**Comment by bergus** [comment]
`getCurrentPosition` is a method of the `navigator.geolocation` object, and like any other callback function you have to bind it to its context.

**Comment by phpnode** [comment]
@vincaslt you have a couple of problems here, **firstly** that error is happening because you are treating a *method* as if it were a *function*. The difference between the two is that a method cares about the value of `this`, which is being lost in this case. 

Taking Bluebird completely out of the picture, the following will fail with the exact same error:
```js
var getLocation = navigator.geolocation.getCurrentPosition;
getLocation(result => console.log(result)); // Illegal Invocation
```

You need to preserve the context, by adding a second argument to your `promisify()` call (Note: This won't actually work in your case, see below.)

```js
var getLocation = Promise.promisify(navigator.geolocation.getCurrentPosition, navigator.geolocation);

getLocation().then(result => console.log(result)); // no illegal invocation error, but weird behaviour, WTF?
```

Your **second** issue is that `getLocation()` is a browser API and does not take a node style callback, so `promisify()` isn't going to work at all in this case! You need to fall back to the promise constructor:

```js
var getLocation = new Promise(function (resolve, reject) {
  navigator.geolocation.getCurrentPosition(resolve, reject);
});
```
