### ISSUE TITLE
isNode check is legacy

### ISSUE THREAD

**Issue by marudor** [petkaantonov/bluebird#1226]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
All

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
All

3) Did this issue happen with earlier version of bluebird?
Yes

Based on the specification (http://www.ecma-international.org/ecma-262/6.0/#sec-object.prototype.tostring) the toString check is not really reliable.
Background: 
Jest (https://github.com/facebook/jest) modifies the process object for mocking. (https://github.com/facebook/jest/blob/master/packages/jest-util/src/installCommonGlobals.js#L34) This throws the check off. With Node 5+ jest can mock the process object in a way that passes the bluebird isNode check. For Node 4 and ealier this is not possible. (As the well known symbol toStringTag does not exist)
Sadly I did not come up with a perfect way to detect.
But using the global Object instead of process would probably already work way better.

**Comment by benjamingr** [comment]
Hey, we realize you can mock this with `toStringTag` but I am unsure if anyone actually abuses this yet.

As soon as someone figures this out and abuses it we'll have to do something different. Until then - I think we're good to go.

**Comment by marudor** [comment]
@benjamingr I did a PR for Jest that uses @@toStringTag cause this checks actually fails to detect it properly. IT will run the browser path.
Sadly on Node 4 or older we do not have @@toStringTag.
So changing it would be really nice.

**Comment by petkaantonov** [comment]
If someone wants to fake process object to throw the check off, then let them.

**Comment by marudor** [comment]
Its not to throw the check off.
It is needed as jest has the ability mock timers and has to modify process for that.
We do not want to throw the check off. We just have to modify process. Therefore the check will fail although we want it to pass.
For node 5+ we can fix it ourself.
For Node 4 and older we can not.

**Comment by petkaantonov** [comment]
I don't understand, why do you need `{}.toString.call(process)` to return different value than `"[object process]"`?

**Comment by marudor** [comment]
We do this: ```Object.assign({}, process)```
This automatically changes the ```@@toStringTag``` value of the Object. Therefore ```.toString``` does not return ```[object process]``` anymore.
If we could we would change the ```@@toStringTag``` of this new Object to match process. Sadly this is not possible without the common Symbol ```toStringTag```
That is not available in Node 4.

Therefore we can not pass the isNode check of bluebird anymore. Although we still run on node and would like it to pass. As the browser paths of bluebird crash.

**Comment by petkaantonov** [comment]
Ok, I guess we could change it to `typeof process == "object" && typeof process.nextTick == "function"`?

**Comment by benjamingr** [comment]
@petkaantonov that would fail for electron probably, and a bunch of other things.

**Comment by petkaantonov** [comment]
electron has `process` and `process.nextTick` but not `"[object process]"`? you sure?

**Comment by benjamingr** [comment]
I don't understand - you want to mock "process"- bluebird has been out there since node 0.10, you're asking for something in Node 4 in order to mock `isNode`. Now, bluebird uses `isNode` in order to test things you typically can't mock.

We do however support setting the scheduler through `Promise.setScheduler` where you can inject your own timing. You can override `setTimeout` for delay or swap `Promise.prototype.delay` and `Promise.prototype.timeout` for your own implementation altogether.

I don't mind helping you with this at all if you require assistance. I'm against changing the process check and I warn you that your code _will_ break if you override it for Node 5+.

**Comment by benjamingr** [comment]
@petkaantonov 
> electron has process and process.nextTick but not "[object process]"? you sure?

I think it's an ordinary object for electron or nw, I can check if you'd like but I recall we had issues with it a few years ago.

**Comment by marudor** [comment]
@benjamingr it is not really a jest specific issue.
I'm not a jest dev either.
I use jest and I use bluebird. I just noticed that some tests now fail due to this problem. With Node 5+ I fixed it on jests side with a PR.
It just happens that if you use jest and bluebird it fails due to some stuff jest does.

As Jest doesnt use bluebird itself it cant really setScheduler on bluebird. Nor should jest expect bluebird users to do that.
As the spec also says this type of test is legacy I just though bluebird could change it help everyone :)

**Comment by benjamingr** [comment]
@marudor if you have a better  test suggestion I'm all ears - everything else we used broke in various things. Remember bluebird runs everywhere - we run on Java servers in Nashhorn, we run in Node, we run in browsers from IE6 (Even Netscape 7 works), we run in electron and in nw and in embedded devices where memory is critical. 

All of those need to work with the new check. If Jest doesn't work with that there is nothing we can do about it but obviously something broke on _their_ side since Jest used to use bluebird itself back in 2015.

**Comment by petkaantonov** [comment]
If there is process and nextTick why not assume it's node @benjamingr
