### ISSUE TITLE
console.warn causes error and swallows message in Edge

### ISSUE THREAD

**Issue by JoshMcCullough** [petkaantonov/bluebird#1377]
1) What version of bluebird is the issue happening on? 3.5.0
2) What platform and version? Edge 40.15063.0.0
3) Did this issue happen with earlier version of bluebird? Yes, with 3.4.1, at least.

In Edge, this line appears to cause a console error: https://github.com/petkaantonov/bluebird/blob/fdd44ee3af6d4fc2570a0f877ca82805a477c6b8/src/debuggability.js#L908

```
console.warn("%c" + message, isSoft ? "color: darkorange" : "color: red");
```

![image](https://cloud.githubusercontent.com/assets/4859660/25465096/587ffb7c-2ace-11e7-9077-5a395c1c9b1b.png)

Even though it seems perfectly valid.

**Comment by halfninja** [comment]
The error isn't actually at this line - there's an "Unhandled rejection SyntaxError" error somewhere else, and it's just being surrounded by the text `%c` and `color:red` because Edge doesn't understand how to use those to print colours. So there is a minor bug in that it shouldn't try to use the `%c` formatting syntax on Edge, but it's not actually the cause of the rejection.

**Comment by JoshMcCullough** [comment]
You're right, there was another error in the code which caused this confusion. Closing...
