### ISSUE TITLE
Not possible to monkey patch Promise constructor

### ISSUE THREAD

**Issue by benny-medflyt** [petkaantonov/bluebird#1427]
Bluebird's Promise constructor seems to aggressively prevent itself from being monkey patched (the `check` function).

Relevant:
http://bluebirdjs.com/docs/error-explanations.html#2.-you-are-trying-to-subclass-promise

I've tried everything but can't figure out how to bypass this.

The [scoped prototypes](http://bluebirdjs.com/docs/features.html#scoped-prototypes) feature isn't helpful in this situation.

We want to be able to override the Promise constructor. Why does Bluebird fight so hard against this? And more importantly: how can it be done anyway?

I'm using Node.js

Thank you

**Comment by benjamingr** [comment]
Don't subclass `Promise`. Why are you trying to override the promise constructor?

 - If it's for instrumentation, check the monitoring feature.
 - If it's for adding functionality - used scope prototypes.
 - Otherwise use composition.

Composition:
```js
function MyPromise(executor) { 
  // do whatever here
  return new Promise(executor);
}
```

Then when you do `new MyPromise` you get a hook.

**Comment by benny-medflyt** [comment]
How can I use composition, but then replace the global Promise with MyPromise? Doesn't seem to work right :(

Thank you

**Comment by benjamingr** [comment]
Oh, you can set `global.Promise` in Node to an instance with a scoped prototype.
