### ISSUE TITLE
Getting warning on every call

### ISSUE THREAD

**Issue by clang676** [petkaantonov/bluebird#1450]
Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
latest

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
node.js: v8.4.0

3) Did this issue happen with earlier version of bluebird?
unsure

Warnign message:
(node:15060) Warning: a promise was created in a handler but was not returned from it, see http://goo.gl/rRqMUw      
    at Function.Promise.attempt.Promise.try (C:\Sites\...\...\node_modules\bluebird\js\release\method.js:29
:9)       
                                                                                                           
this is happening on my post calls and get calls?

**Comment by benjamingr** [comment]
Please do not open support requests in the GitHub issue tracker - you may open one in StackOverflow instead.

**Comment by adamreisnz** [comment]
This is not a support request from what I can tell. I am also seeing these warnings all over the place now, even in code originating from 3rd party libraries, because I'm using bluebird as a `global.Promise`.

I know what's causing them, but this didn't use to trigger a warning so I wonder why suddenly it does. I know what I'm doing, and I don't need to be warned about runaway promises.

**Comment by adamreisnz** [comment]
Apparently there is this:
