### ISSUE TITLE
Option to remove eval optimization that causes unreachable code warning in Firefox.

### ISSUE THREAD

**Issue by Giwayume** [petkaantonov/bluebird#1504]
1) What version of bluebird is the issue happening on?
3.5.1

2) What platform and version?
Firefox 58.

3) Did this issue happen with earlier version of bluebird?
Yes

I realize why this optimization exists. #899 #1234

I am requesting you only provide this optimization in the minified bluebird.min.js (for those looking for performance improvements), and leave it out of bluebird.js (for those looking for a proper spec-compliant library without compiler hacks). I am tired of seeing the warning message.

**Comment by gabrielps** [comment]
Up :smiley:

**Comment by mdr1384** [comment]
I disagree. Some of us do our own minification because we combine dozens of JS files together to get a single JS file for the entire page, and we get better compression when all the unminified files are concatenated first. We would lose the "optimization" if you didn't put it in the unminified version. I don't understand why anyone cares about the warning if it only happens in dev mode.

**Comment by Giwayume** [comment]
I don't personally care how it's done, I'm just asking for the _option_ with it removed. You don't agree with losing a compiler hack, I don't agree with having compiler hacks in the first place that are supposed to be bad code on paper. Compilers change and ultimately the spec drives it.

**Comment by benjamingr** [comment]
This was actually fixed a while ago when we made toFastProperties work with new v8

**Comment by Giwayume** [comment]
Alright
