### ISSUE TITLE
observables-baconjs-bacon.js.js is producing a false positive on Anti-Virus Server

### ISSUE THREAD

**Issue by Krizziebb** [petkaantonov/bluebird#1567]
1) What version of bluebird is the issue happening on? 
Most up to date branch

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
It's being used within the most recent HumHub release

3) Did this issue happen with earlier version of bluebird?
Not sure.

The only additional information i have been provided is below - 

Warning name - TROJAN-downloader.script.generic

files: observables-baconjs-bacon.js.js

Directories: 
/protected/vendor/boer-asset-bluebird/benchmark/doxber-sequential/
/static/assets/4fe89177/benchmark/doxber-sequential/

**Comment by benjamingr** [comment]
Checking

**Comment by benjamingr** [comment]
Well, first of all it looks like `baconjs-bacon.js.js` hasn't been updated in 4 years and there is no actual security risk. That's the first thing I wanted to figure out.

We can remove the benchmarks from the deployed version if that would help - though I think this is something for the anti-virus to fix.

**Comment by benjamingr** [comment]
Going to ping the node security team just in case.

**Comment by lirantal** [comment]
@Krizziebb waiting for your input, happy to hear more about this if you can share.

**Comment by lirantal** [comment]
Looks to me like they bundle the bluebird library through bower perhaps.
No idea why the AV software is reporting an issue with that benchmark file though. If the user can be prompted to chime on here for more help perhaps but otherwise don't think there's anything special to take action upon.

Thanks for reaching out Tyler and happy holidays too!
