### ISSUE TITLE
Issue resolving promise in IE 11

### ISSUE THREAD

**Issue by lancescole** [petkaantonov/bluebird#1620]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
3.7.1

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Node 10.16.3
npm 6.12.0
IE 11.1006.17134

3) Did this issue happen with earlier version of bluebird?
Bluebird 3.5.0 works 

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

IE just doesn't load. We reverted to 3.5.0 and it works. It hangs on the following code:
return function(promise) {
    promises.push(promise);
    if (iframeSetTimeout) {
        iframeSetTimeout(unhandledRejectionCheck, 1);  // Here is the error
    } else {
        checkIframe();
    }
};

The error says: Can't execute code from a freed script

**Comment by zumankii** [comment]
Same issue here; works with bluebird@3.5.5, but fails with bluebird@3.7.1 in Edge and Firefox.

**Comment by binki** [comment]
Sounds similar to #1623. However, in Firefox, the issue is detectable synchronously.

In Edge-44.19030.1.0 (EdgeHTML-18.19030) and iexplore-11.1.19030.0 (11.0.160), the iframe’s freeing seems to be nondeterministic/asynchronous, so reproducing is a bit more unreliable. For example, in https://jsfiddle.net/97v6twoe/ , I get the error after waiting 4 seconds on the initial load. But I don’t get it later if I hit the Run button.

**Comment by binki** [comment]
Pretty sure https://github.com/petkaantonov/bluebird/commit/f88044507cb5ad8a3a27b219c7ea4e5a2d1e7207 also fixed this issue

**Comment by lancescole** [comment]
I believe that this has been fixed in the latest release. You can close it.
