### ISSUE TITLE
Partial builds with NPM package?

### ISSUE THREAD

**Issue by gaearon** [petkaantonov/bluebird#254]
I'm using Webpack now and I'm wondering if something like “custom builds” is possible when using NPM version of the package. Since Bluebird is already modularized, it would be nice if there was some way of excluding features I'm not using.

For now I'll fork it and do

```javascript
require('./timers.js')(Promise,INTERNAL);
// require('./any.js')(Promise,Promise$_CreatePromiseArray,PromiseArray);
// require('./race.js')(Promise,INTERNAL);
require('./call_get.js')(Promise);
// require('./filter.js')(Promise,Promise$_CreatePromiseArray,PromiseArray,apiRejection);
// require('./generators.js')(Promise,apiRejection,INTERNAL);
// require('./map.js')(Promise,PromiseArray,INTERNAL,apiRejection);
// require('./nodeify.js')(Promise);
// require('./promisify.js')(Promise,INTERNAL);
// require('./props.js')(Promise,PromiseArray);
// require('./reduce.js')(Promise,Promise$_CreatePromiseArray,PromiseArray,apiRejection,INTERNAL);
// require('./settle.js')(Promise,Promise$_CreatePromiseArray,PromiseArray);
// require('./some.js')(Promise,Promise$_CreatePromiseArray,PromiseArray,apiRejection);
require('./progress.js')(Promise,isPromiseArrayProxy);
require('./cancel.js')(Promise,INTERNAL);
```

but it would be cool to have a better solution.

Edit: Oh wait, I can't fork it and edit since this is generated.

**Comment by benjamingr** [comment]
@petkaantonov let's discuss supporting webpack, what's required on our end? Webpack is pretty popular now and if it's not a lot of work let's consider supporting it and systemjs.

@gaearon has ignoring it with the plugin been working out fine for you? Have you done something differently?

**Comment by gaearon** [comment]
@benjamingr 

I think I was just using my fork at the time, and later I removed Bluebird completely after we started relying much less on Promises on the client side. But the approach looks good to me.

**Comment by petermikitsh** [comment]
If you use the `IgnorePlugin`, as suggested above, the build will succeed, but the runtime will throw an  exception when the module isn't found.

I've added the following to my webpack config:

```js
new webpack.IgnorePlugin(
  /\.\/(timers|any|race|call_get|filter|generators|map|nodeify|promisify|props|reduce|settle|some|progress|cancel)\.js/,
  /node_modules\/bluebird\/js\/release/
)
```

And I'm importing bluebird like this:

```js
window.Promise = require('bluebird/js/release/bluebird');

Promise.config({
  longStackTraces: true
});
```

For my specific use case, I'm only using Bluebird because I want long stack traces. So I'm not totally confident which files I could potentially include and exclude, since I'm not too familiar with the source code, but I omitted the files suggested above.

Excluding map causes this runtime exception:

![screen shot 2018-08-13 at 4 50 09 pm](https://user-images.githubusercontent.com/1571918/44064267-0078c966-9f19-11e8-8263-f5df9fa5741e.png)

![screen shot 2018-08-13 at 4 50 19 pm](https://user-images.githubusercontent.com/1571918/44064278-0ce3101c-9f19-11e8-8134-55f34aafeeec.png)

If I could produce a build that was just a wrapper on top of regular Promises, but had long stack tracing, that would be ideal. Full stack traces are very useful identifying and squashing bugs in production.

Including the additional functionality of Bluebird that I am not using in my client bundle is wasting bandwidth and lowers initial page loading times.

**Comment by benjamingr** [comment]
> For my specific use case, I'm only using Bluebird because I want long stack traces. So I'm not totally confident which files I could potentially include and exclude, since I'm not too familiar with the source code, but I omitted the files suggested above.

Just an update that we're working with v8 to have long stack traces in production by default for native promises. My approach (personally) over the last few years has been to try and improve the native promises situation.

That said - you can always just run the partial build (with the build tool) and `require` that.

**Comment by petermikitsh** [comment]
<img width="379" alt="screen shot 2018-08-14 at 7 47 35 am" src="https://user-images.githubusercontent.com/1571918/44098989-6f33c284-9f96-11e8-8b73-158d6e604905.png">

v3.5.1 (latest) actually ships the core (partial) build to NPM-- no building necessary. Switched to that, and shaved off a few kb's. Thanks.
