### ISSUE TITLE
promisify nodemailer-smtp-transport

### ISSUE THREAD

**Issue by divramod** [petkaantonov/bluebird#333]
Hey, i try to get into bluebird. can you help me with wrapping nodemailer-smtp-transport?
I am using koa and tried a lot but couldnt find the solution.
Here is my code:

<code>
    var nodemailer = require('nodemailer');
    var smtpTransport = require('nodemailer-smtp-transport');
    var Promise = require("bluebird");

```
exports.create = function*() {
  var transporter = nodemailer.createTransport(smtpTransport({
      host: 'smtp.myemailservice.de',
      port: 25,
      auth: {
          user: 'user',
          pass: 'pw'
      }
  }));

  var mailOptions = {
      from: 'Fred Foo ✔ <foo@blurdybloop.com>', // sender address
      to: 'email@email.com', // list of receivers
      subject: 'Hello ✔', // Subject line
      text: 'Hello world ✔', // plaintext body
      html: 'mail conent'·
  };

  transporter.sendMail(mailOptions, function(error, info) {
      if (error) {
          this.body = error;
      } else {
        this.body = info.response;
      }
  });
```

  };
</code>

**Comment by ricardograca** [comment]
I'm also having trouble promisifying nodemailer. However I'm using the stub transport like so:

    var transport = require('nodemailer-stub-transport')
    var transporter = Promise.promisifyAll(nodemailer.createTransport(transport()))

It always crashes nodemailer and my app. Any ideas?

**Comment by amaanmemon** [comment]
@divramod  can you please send the merge code.. i am facing the same issue

**Comment by ricardograca** [comment]
I was also having the same problem some time ago. The code above is no longer valid. You have to use this:

```javascript
var nodemailer = require('nodemailer')
var transport = Promise.promisifyAll(nodemailer.createTransport({ /* options */ }))
```

Note that if you are trying to use a transport mechanism that is not built-in, there is a small difference. Instead of passing an options object to the `createTransport` method, you pass the external transport directly like so:

```javascript
// Example using the stub transport
var stubTransport = require('nodemailer-stub-transport')()
var transport = Promise.promisifyAll(nodemailer.createTransport(stubTransport))
```

**Comment by amaanmemon** [comment]
@ricardograca i want to sen mail and i am using the following code

var nodemailer = require('nodemailer');
nodemailer.SMTP = {
 host: 'mail.gmail.com',
 port: 25,
 use_authentication: true,
 user: my@example.com',
 pass: '***'
};

var message = {   
    sender: "my@example.com",    
    to:'you@example.com',   
    subject: 'Test Report',    
    html: '<h1>test</h1>',  
};

*******************************************************************
and the below code should return promise because i am using stackify module to execute in sync.

   nodemailer.send_mail(message,   
      function(err) {   
        if (!err) { 
            console.log('Email send ...');
        } else console.log(sys.inspect(err));       
    });

Do you have any solution for this??
