### ISSUE TITLE
Q vs. Bluebird performance

### ISSUE THREAD

**Issue by davidvgalbraith** [petkaantonov/bluebird#381]
Hi! In https://github.com/petkaantonov/bluebird/issues/63, @petkaantonov makes some big statements about Bluebird's performance as compared with Q: it's 100 times faster and uses 5% of the memory. Wow! I've been wondering since I read that, how were such dramatic gains achieved? What were some of the key backend changes that let you more or less preserve Q's semantics while just totally wiping the floor with it in terms of performance? Thanks!

**Comment by ORESoftware** [comment]
@petkaantonov i know this your lib but by inline functions do you mean function declarations/expressions? "inline" is one of those words that can mean different things

**Comment by ORESoftware** [comment]
http://stackoverflow.com/questions/19159703/what-is-the-difference-between-anonymous-and-inline-functions-in-javascript

I guess "inline" functions mean both function expressions and function declarations in JS, but maybe there is some use to the term inline as a catch-all term

**Comment by bergus** [comment]
@ORESoftware  I think the following sentence from the [answer](http://stackoverflow.com/a/19159927/1048572) to the linked question sums it up pretty nicely:

> *An inline function is a function [assigned to a variable] that is created at runtime instead of at parsetime.*

His examples are wrong however, they're not showing the problem, and it doesn't make a difference whether the function is created using a declaration or an expression (anonymous or not). The key part is that the function is created at runtime - multiple times, within ("inline" of) another function that gets called multiple times.

**Comment by phpnode** [comment]
"inline" in this context refers to V8's ability to inline the body of another function into its callsite. For a simple example, V8 can transform:

```js
function doSomething (a, b) {
  return add(a, b);
}

function add (a, b) {
  return a + b;
}
```

into

```js
function doSomething (a, b) {
  return a + b;
}
```

(V8's transformation happens using an intermediate representation, it doesn't manipulate the actual source)

Because V8 was able to remove the overhead of the function call, `doSomething()` will now be significantly faster.

Petka's sentence refers to purposely writing code which V8 can inline, avoiding any constructs which prevent it.

**Comment by spion** [comment]
Hmm. I understood it as "avoiding object allocations (those caused by creating closures in particular) at all costs get you pretty far" - [more info in Trevor's article](http://blog.trevnorris.com/2013/08/long-live-callbacks.html)

Also AFAIK if the function is not a closure (doesn't refer to things outside its variable scope and is not included in the return result of the enclosing function), V8 will know how to avoid re-allocating it over and over
