### ISSUE TITLE
Unhandled rejection wiki page?

### ISSUE THREAD

**Issue by benjamingr** [petkaantonov/bluebird#424]
Hey, there are several questions such as [this one](http://stackoverflow.com/q/27737115/1348195) where users forgot a `return` in a promise API. 

I'm wondering if bluebird should link to a page containing common causes for that in the wiki and whether or not we should link to it.

Mainly, such a page would include:

 - What's a "possibly" unahdled exception? (detected automatically)
 - What are common causes for one? (missing return, etc)
 - How to find where it originated? (long stack traces)

What do you think? Is it viable?

**Comment by spion** [comment]
Definitely viable. How its detected could also be discussed in more detail. 

One unfortunate thing is that thenlint isn't smart enough to detect this problem (I stopped working on it since I switched to typescript, as typescript tells me immediately that I'm trying to use undefined as a promise)

**Comment by petkaantonov** [comment]
Forgetting `return` rarely causes a possibly unhandled error though

**Comment by bendrucker** [comment]
In reality checking the return value isn't always viable. Two edge cases that come to mind:

* things like gulp that use [async-done](https://www.npmjs.com/package/async-done) and allow multiple async styles
* things like [emit-then](https://www.npmjs.com/package/emit-then) where you can either do something synchronous or return a promise

Regarding:

> If a library calls validateSave here, it probably should have thrown for returning `undefined`.

That's not feasible for Bookshelf. Because events are wrapped in promises, you can do something synchronous (including `throw`). So there's nothing that the library can do to prevent user error there.

**Comment by benjamingr** [comment]
@bendrucker another alternative is for Bookshelf (or checkit) to log undefined was returned by default.

**Comment by benjamingr** [comment]
Lots of questions on SO about missing `return`s causing stuck promises, I wonder if there is a legit use case for a fulfilled promise that is never unwrapped. Anyone?

**Comment by benjamingr** [comment]
Meh, this needs more work as it stands it's a bad idea.
