### ISSUE TITLE
Unable to chain promisifyAll request function

### ISSUE THREAD

**Issue by johnymonster** [petkaantonov/bluebird#470]
```javascript
var Promise   = require('bluebird'),
    request   = Promise.promisifyAll(require('request'))
Promise.props({"url":"http:google.com"}).then(request.getAsync).spread(function(response, body){
});
```

the above throws a TypeError

```
Possibly unhandled TypeError: Cannot call method 'get' of undefined
    at ret (eval at makeNodePromisifiedEval (....../node_modules/bluebird/js/main/promisify.js:177:12), <anonymous>:15:22)
```

however, if I modify it then it works

```javascript
Promise.props({"url":"http:google.com"}).then(function(result){
return request.getAsync(result);
}).spread(function(response, body){
console.log(body);
});
```

**Comment by petkaantonov** [comment]
Because `promisifyAll` is also used to promisify modules and classes whose instances don't exist at promisification time, the methods cannot be bound to any particular `this` value` even though in the singleton case (`request`, `fs` etc) that is possible. So they use whatever `this` is at call time, which is `request` when doing `request.getAsync()` but is undefined when doing `var get = request.getAsync; get()` as per how javascript `this` works.

So it would need to be an option to `promisifyAll` (e.g. `promisifyAll(..., {singleton: true})`)

**Comment by benjamingr** [comment]
@petkaantonov calling it a singleton is rather misleading (it's just a namespace and not really a singleton) - what about `{bindContext: true}`?

**Comment by johnymonster** [comment]
Sorry fat thumbed thus on my phone.

**Comment by petkaantonov** [comment]
@johnymonster so what is your opinion? Would you use a bindContext option to be able to pass request.getAsync directly into a then?
