### ISSUE TITLE
What is the zalgo build?

### ISSUE THREAD

**Issue by ysmood** [petkaantonov/bluebird#485]
When should I use it and when should not?

**Comment by benjamingr** [comment]
You should never use it.

The Zalgo build does not defer execution to the next cycle in promise
resolution. It exists in order to prove to people who think that there is a
performance benefit in that that the benefit is marginal.

For example in the Zalgo build:

```js

myPromise.then(function(el){
     alert("Hello");
});
alert("World");
```

It's possible that "Hello" will output before "World" depending on whether
or not `myPromise` is already resolved.

In general you should never use the Zalgo build for anything - it's a proof
of concept. You can read more details about it in the readme.

**Comment by ysmood** [comment]
Thanks, I found it in the sync build section.
