### ISSUE TITLE
Bluebird being used by 3-rd party library, renders nodejs domains useless?!

### ISSUE THREAD

**Issue by sebastianhoitz** [petkaantonov/bluebird#518]
I'm using sequelize as a dependency in my app which uses bluebird internally.

However, for some reason this also changes the behavior of MY app. I can't use the nodejs domains anymore for catching things like TypeErrors.

I only get a "Possibly unhandled TypeError: ..." but the domains error handler is not getting called.
What can I do?

**Comment by petkaantonov** [comment]
That means you are using promises, or the error is coming internally from sequelize, but the code causing that error is definitely using promises.

**Comment by bendrucker** [comment]
First off, Bluebird's default behavior behavior is to log possibly unhandled errors because they almost always indicate a developer error. There are very few cases where you don't want to handle an error at its source and it's generally agreed upon that domains will be replaced, though their replacement isn't clear. 

If you really wanted to trigger domain logic, attach a handler using [onPossiblyUnhandledRejection](https://github.com/petkaantonov/bluebird/blob/master/API.md#promiseonpossiblyunhandledrejectionfunction-handler---undefined) and then emit an error on `domain.active`. Wouldn't recommend doing that though.

**Comment by benjamingr** [comment]
Domains are deprecated - avoid them in new code.

As for promises - promises are throw safe - they make domains useless but in a positive way. You can handle errors with `.catch` and obtain readable, performance and throw-safe code that works consistently.
