### ISSUE TITLE
Providing context for the constructor callback

### ISSUE THREAD

**Issue by gcaini** [petkaantonov/bluebird#530]
Is there any better way to do the following:

new Promise(function(resolve, reject) { ... }.bind(this));

The reason I ask is because so far Promise.try, Promise.bind, and Promise.method have taken care of preserving the value of "this" for me, without having to resort to Function.prototype.bind. And lodash does the same - _.each takes a context argument for example. So it seems to me that libraries are almost encouraging me to not use Function.prototype.bind, and I was surprised to come across a construct that requires it.

**Comment by petkaantonov** [comment]
`new Promise` is almost always an anti-pattern, if I can make its use hard then I'll take it. It is only needed in library level code to wrap non-standard async APIs.

**Comment by gcaini** [comment]
Thanks. Just to doublecheck, is there a better way to obtain a promise for, say, an XMLHttpRequest?

**Comment by petkaantonov** [comment]
If you are using jQuery $.ajax returns a promise which you can convert to bluebird using `Promise.resolve($.ajax(..:))`, similar with angular or any framework you are using.

If you are using pure XMLHttpRequest you should implement a wrapper in your utility library, this will require using new Promise once. Application code should simply call the wrapper and chain the returned promise instead of using new Promise.

**Comment by benjamingr** [comment]
@gcaini the new DOM HTTP request API (called fetch) already returns promise so you can just resolve them - that said `bind`ing is fine here.

**Comment by phpnode** [comment]
Since fetch is basically ungooglable - https://www.npmjs.com/package/whatwg-fetch

**Comment by benjamingr** [comment]
@phpnode it's the first google result for "fetch API" :dancer:
