### ISSUE TITLE
Browser build stopped working on node since v2.9.24

### ISSUE THREAD

**Issue by depoulo** [petkaantonov/bluebird#587]
When using the browser build of v2.9.24 in node (verified under v0.12.2), I get
```
Uncaught TypeError: Cannot read property 'configurable' of undefined
      at Object../queue.js (packages/vendor.bluebird/bluebird.js:129:24)
```
This error does not occur in v2.9.23, and, strange enough, not on Windows (still node v0.12.2) even with v2.9.24.

Perhaps related to #559, the failure seems to come from [this change](https://github.com/petkaantonov/bluebird/compare/v2.9.23...v2.9.24#diff-5), which I don't understand anyhow: How can `Object.getOwnPropertyDescriptor(EventsModule, "usingDomains");` not fail if `!EventsModule.usingDomains`?

**Comment by niwibe** [comment]
+1 
I'm also found this error!

**Comment by petkaantonov** [comment]
Why would you use browser build in node?

**Comment by niwibe** [comment]
I'm using it as a dependency in clojurescript library, that can be used in browser and in nodejs environments. Currently the main target is browser but tests are running in nodejs.

**Comment by depoulo** [comment]
Isomorphic code here as well. Pretty heavy if I'd had to add environment dependend requirejs config for a promise library.

**Comment by petkaantonov** [comment]
That's not what the browser build is for, the browser build is for people who like to use simple script tags to include the library. You should use the node module just like you are using any other npm module.

**Comment by niwibe** [comment]
@petehunt is very common task run some browser code in node for tests purposes, and hanving explicit different versions depending on environment is slightly complicated.

In my use case, the main target is a browser, and I'm using the browser version one, but I run almost all tests in node because in unit tests I don't need nothing browser related and run tests in node is much faster that turn up some browser engine. With this desition you are forcing all users that using this library in this manner to use phantompjs or similars or switch to an other library.

In my other use case, I'm maintaining a clojurescript library that uses bluebird on its internals, and it can be used in different environments that I can not have control. Additionally, clojurescript projects tends not use npm modules but may run perfectly on nodejs environments, with desition to not fixin that, you are also forcing to not use your library.

I'm ok with your desition, but please, reconsider fixing it instead of leaving as invalid ;)

**Comment by domenic** [comment]
Although I agree with @petkaantonov that you should not be using the browser build in this way, I still find the error itself to be strange and hard to understand why it's happening. (At first I thought it would be because the browser build uses browser features like MutationObserver or something, but the stack trace in the OP does not point to that.)

May I suggest trying with io.js? Node.js 0.12 uses a very old V8 version and I wouldn't be surprised if it has weird bugs.

**Comment by niwibe** [comment]
@domenic the same exception happens with iojs-1.5.x and iojs-1.7.x

**Comment by domenic** [comment]
So bizarre. Would be curious if anyone root-causes this, just so we can better understand it.

**Comment by niwibe** [comment]
As far as I can understand, that happens that because browser version of events module does not contains the usingDomains property (see https://github.com/petkaantonov/bluebird/blob/master/src/async.js#L77)

The fix is as simple how check the descriptor value previously to access it:

```diff
- if (!descriptor.configurable) {
+ if (descriptor !== undefined && !descriptor.configurable) {
```

**Comment by domenic** [comment]
We should just fix the browser version of the events module.

**Comment by niwibe** [comment]
Yes, seems a better approach ;)

**Comment by petkaantonov** [comment]
The browser build should only work in browsers, it's free to make optimizations by removing code that is not necessary in browser and make assumptions like the existence of dom. So even if it appears to work it probably doesn't.

**Comment by domenic** [comment]
Yeah, I think if people want to be doing this they should use jsdom. Even then it will only work if jsdom and browserify are perfect. (Here we found a case where browserify is imperfect; I imagine other cases would reveal jsdom imperfections.)

**Comment by petkaantonov** [comment]
So this is actually a browserify bug for not shimming events module entirely right?

**Comment by domenic** [comment]
That is what it sounds like

**Comment by petkaantonov** [comment]
> The fix is as simple how check the descriptor value previously to access to its properties:

This is stupid because this code is inside `isNode` check, so it must be safe for the code to think it's node. The correct place to fix this is in browserify.

**Comment by depoulo** [comment]
OK it's basically because of all these `isNode` branches that I thought it could run in node just as well. So why don't we remove those altogether from the browser build in order to save unneeded bytes?

**Comment by niwibe** [comment]
Removing it from the browser build, maybe it will make impossible use browser build in node ;)

**Comment by petkaantonov** [comment]
> OK it's basically because of all these isNode branches that I thought it could run in node just as well. So why don't we remove those altogether from the browser build in order to save unneeded bytes?

The isNode branches are because this is a npm library that can be required in browsers (via browserify or webpack), like most  npm modules. If you use node you use npm. However most npm modules dont ship with a separate optimized build for browser *at all* so how are you using them isomorphically? Your should apply your answer to how you use bluebird.

**Comment by darkyen** [comment]
I found the same error on Azure...

**Comment by depoulo** [comment]
Thank you for your patience @petkaantonov. So basically the browser build is for people who like to use simple script tags to include the library, either via global export or requirejs, plus for usage in a browserify way.

**Comment by dougwilson** [comment]
Excuse me, this is also breaking in Node.js all of a sudden...
```
$ node -pe "require('bluebird')"

node_modules\bluebird\js\main\async.js:77
        if (!descriptor.configurable) {
                       ^
TypeError: Cannot read property 'configurable' of undefined
    at Object.<anonymous> (node_modules\bluebird\js\main\async.js:77:24)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at module.exports (node_modules\bluebird\js\main\promise.js:13:13)
    at Object.<anonymous> (node_modules\bluebird\js\main\bluebird.js:9:39)
    at Module._compile (module.js:449:26)
```
There is no problem at all with 2.9.23...

**Comment by zaggino** [comment]
This makes things complicated a bit, I have an electron app (which has both browser and node globals available) and need to use the browser version (without hiding the process global) ... how can I work around this?

**Comment by petkaantonov** [comment]
@zaggino use .25

**Comment by zaggino** [comment]
Missed that update, thanks!
