### ISSUE TITLE
Why does promisifyAll modify the actual API instead of returning a new version of it?

### ISSUE THREAD

**Issue by chevex** [petkaantonov/bluebird#621]
Just curious. I love this library because you guys seem to think a lot about the details. I'm sure you have a reason for doing it the way you're doing it, but it feels like a tiny bit of an anti-pattern to modify the original API rather than just return a new promisified version of it. Kind of like how plain old `promisify` works, by returning a new function you can use. Does it have something to do with non-singleton APIs?

Thanks and keep up the great work!

**Comment by petkaantonov** [comment]
If you actually have a singleton API, it's trivial to create a promisified copy e.g. `Promise.promisifyAll(Object.create(require("fs")))`

However, most of the time you have classes and creating your own copies of those doesn't work because the code uses the old classes. And you can't just promisify every instance of a class separately at runtime because it's prohibitively expensive (it takes 50ms to promisify fs module for instance).

**Comment by chevex** [comment]
That makes sense. Thank you for explaining. I didn't realize you could make easy copies of objects using `Object.create`. I've always used "extend" libraries to do that, but now I see that I only need those if I actually want to copy and *extend* the object. Thanks!

**Comment by petkaantonov** [comment]
The reason `Object.create` works here to make a copy is because promisifyAll walks prototype chains instead of own properties only.

**Comment by chevex** [comment]
:+1:
