### ISSUE TITLE
Latest version 2.9.26 cause mocha tests that use sinon.useFakeTimers to fail

### ISSUE THREAD

**Issue by demetriusnunes** [petkaantonov/bluebird#631]
My test suite uses sinon.useFakeTimers in some tests.

After the latest version bump to 2.9.26, all tests using sinon.useFakeTimers fail. Reverting back to 2.9.25 fixes the problem.

**Comment by petkaantonov** [comment]
Do you have some repro code? The last patch had nothing to do with timers

**Comment by dmethvin** [comment]
It's probably 23d1b872c1fa580a5285a9aeee15611f4edb30c0, that changed the binding time of `setImmediate` which is one of the methods that sinon fakes. If you are loading sinon after Bluebird you're getting sinon's fake method now. I'm not sure `setImmediate` should be faked because it's more of a low-level task scheduler. See https://github.com/cjohansen/Sinon.JS/issues/527 for some ways to deal with it.

**Comment by petkaantonov** [comment]
@dmethvin I guess so, their documentation says nothing about setImmediate :(
