### ISSUE TITLE
Promise.all().catch catches only one rejection (when multiple are thrown)

### ISSUE THREAD

**Issue by groovy354** [petkaantonov/bluebird#633]
Consider the following code:
```js
Promise.all([Promise.rejected("1"), Promise.rejected("2")])
.catch(function(e){console.log(e)})
```
The output is:
```
"1"
```

But what I'd expect to get is:
```js
["1", "2"]
```

Is there an additional parameter to Promise.all that I'm missing that would help achieve that?

**Comment by benjamingr** [comment]
There is nothing we can do about this - this is mandated by the ECMAScript specification and we can't break compatibility with ES6. In addition keep in mind that `.all` rejects as soon as a single promise rejects so you'd actually need another promise (or async iteration mechanism) in order to access all the rejections since they're not ready yet. 

In bluebird's own methods an aggregation is returned and you can access all the errors. You can also use `.settle` and `.reflect` if you'd like. 

(Also note that it's Promise.reject and not Promise.rejected)

Also note - that support questions are better asked on Stack Overflow - please ask there next time.

**Comment by eminoda** [comment]
there is no way?

**Comment by benjamingr** [comment]
@tacnoman as explained above, you can use `.reflect` for this or `.settle`. 

The issue tracker is not the correct place to ask support questions. Cheers.
