### ISSUE TITLE
Memory issue with Promise.map (solved by .delay(0))

### ISSUE THREAD

**Issue by wachunga** [petkaantonov/bluebird#653]
bluebird 2.9.27
nodejs 0.12.4

Using `Promise.map` on large arrays eats up a lot memory, presumably due to the lengthy promise chain. But during testing I discovered that adding `.delay(0)` totally solves the "leak" (see below).

Seems like there's a performance issue with how Promise.map works by default. Certainly we shouldn't have to resort to `.delay(0)`?

```javascript
var Promise = require('bluebird');

var ENTITIES = 500000;
var STACK_DEPTH = 10;
var options = { concurrency: 50 };

var start = Date.now();

function reportMemory() {
	var heap = process.memoryUsage().heapUsed / (1024 * 1024);
	var memPerSecond = heap / (Date.now() - start) * 1000;
	process.stdout.write(heap.toFixed(2) + 'mb (' + memPerSecond.toFixed(2) + 'mb/s) \r');
}

function add(value) {
	return new Promise(function (resolve) {
		if (value % (STACK_DEPTH/10) === 0) {
			reportMemory();
		}
		resolve(value + 1);
	}).then(function (newValue) {
		return newValue >= STACK_DEPTH ? newValue : add(newValue);
	});
}

(function () {
	var entities = new Array(ENTITIES);

	Promise.map(entities, function () {
//		return add(1); // leaks
		return add(1).delay(0); // does not leak
	}, options).then(function () {
		console.log('done');
		process.exit();
	});
})();
```

**Comment by benjamingr** [comment]
Thanks for reporting!

Is this with long stack traces enabled? Also, can you try in 3.0?

**Comment by wachunga** [comment]
@benjamingr Long stack traces are off as you can see from the snippet. When I turn them on, memory usage keeps going up regardless of any (reasonable) `.delay`.

**Comment by petkaantonov** [comment]
The memory leak is not with promises but with node's streams which appear to only do cleanup after full event loop turns which is why there is no leak when you add `.delay(0)` (which enables node to do cleanup). So funnily the tool you are using to detect memory leak is causing the memory leak. I tested this with node-heapdump.

To see that this code is not leaking, just run it with very small heap size (default is 1400)

```
node --max-old-space-size=16 test.js
```

This will run extremely slowly because the GC needs to constantly do cleanup in order to not exceed the small size limit.

The code used is the same except with very little logging (since it's the logging that leaks):

```js
var Promise = require('bluebird');
console.log(Promise.hasLongStackTraces());

var ENTITIES = 500000;
var STACK_DEPTH = 10;
var options = {concurrency: 50};

var start = Date.now();

function add(value, index) {
    return new Promise(function (resolve) {
        resolve(value + 1);
    }).then(function (newValue) {
        return newValue >= STACK_DEPTH ? newValue : add(newValue, index);
    });
}

(function () {
    var entities = new Array(ENTITIES);

    Promise.map(entities, function (_, index) {
        if (index % 10000 === 0) {
            console.log(index);
        }
      return add(1); // leaks
    }, options).then(function () {
        console.log('done');
        process.exit();
    });
})();
```
