### ISSUE TITLE
(node) warning: possible EventEmitter memory leak detected. 11 listeners added

### ISSUE THREAD

**Issue by DmitrySoshnikov** [petkaantonov/bluebird#661]
We tried switching from `Q` to `bluebird` in the [Jest](https://github.com/facebook/jest) project, and started constantly to get this warning:

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
  at process.addListener (events.js:160:15)
  at process.on.process.addListener (node.js:802:26)
  at /Users/dmitrys/jest/node_modules/bluebird/js/main/async.js:80:25
  ....
```

We ran many tests in parallel, seems many promises are created, but `Q` didn't have this issue.

**Comment by DmitrySoshnikov** [comment]
We can probably fix it in our code by [setMaxListeners(n)](https://nodejs.org/docs/latest/api/events.html#events_emitter_setmaxlisteners_n):

```javascript
process.setMaxListeners(0);
```

Although, probably bluebird may want to do the same in [here](https://github.com/petkaantonov/bluebird/blob/master/src/async.js#L67).

**Comment by PiPeep** [comment]
I'd argue this isn't something that bluebird should do, as it has global side-effects, and because it can already be fixed on the application's (or in this case, jest's) side. Plus, it might cover up real leaks, though 10 seems like a pretty arbitrarily low value. We probably only get the error in jest because of the software's complexity.

**Comment by benjamingr** [comment]
Bluebird is just adding 1 handler here (per instance) if I understand
correctly so it's really not up to bluebird to put that limit at a very
high number because as the previous comment said it might cover up a real
issue.

On Tue, Jun 23, 2015 at 8:17 PM, Benjamin Woodruff <notifications@github.com

**Comment by bergus** [comment]
Well, Bluebird could do
```js
if (process._maxListeners)
    process.setMaxListeners(process._maxListeners + 1);
```
if there is really a need for this.
