### ISSUE TITLE
Any way of forcing the resolution of all promises before executing an error handler?

### ISSUE THREAD

**Issue by pnex2000** [petkaantonov/bluebird#739]
We ran into the issue where .props()/.all() will fail fast when a promise rejects when we would need all promises to be resolved before the error handler being called in order to clean up resources cleanly. Apparently this can be done correctly with .settle(), but we're making a library and .settle() puts the burden of correctly handling promise joining on the user instead of on the library. See here: https://github.com/reaktor/pg-using-bluebird/issues/3

My question is, is there a way to force the resolution of all promises in the error handler instead of the collecting method? Does bluebird even permit that?

**Comment by benjamingr** [comment]
Since `.all` is specified by the ES2015 spec we can't really help you with it. That said, if you use other methods you can get an `AggregateError` instead which lets you access all errors - for example you can use `.some` with the length of the input array.


Please consider using `using` for resource management as it encapsulates all the logic of cleaning up after partial failures (which in my experience is hard to get right). It takes care of many of the common pitfalls. 

Also, in general support questions are best off the issue tracker (in the appropriate support channels, as the contributing file outlines).
