### ISSUE TITLE
Promise.map and co throws TypeError: fn should be a function

### ISSUE THREAD

**Issue by rafaeljesus** [petkaantonov/bluebird#783]
Hey,

I'm refactoring my code base from a full promises api and trying to mix with generators,

But I don't know how to execute a yield operator inside Bluebird.map,

```
exports.saveAll = function* (items, options) {
  options || (options = {})
  options.upsert = true

  return Promise.map(items, item => {
    const gen = function* () {
      const query = createQuery(item)
      const args = [query, item, options]
      return yield collection.findAndModify.apply(this, args)
    }
    return co(gen)
  })
}
```

And somewhere else I call
````
yield Collection.saveAll(items)
```

I'm having this error `TypeError: fn should be a function`

How do I iterate a array of object with bluebird collection api and execute a generator in there?

**Comment by bergus** [comment]
Please ask [support](https://github.com/petkaantonov/bluebird#support) questions on StackOverflow, this issue tracker is for feature requests and bug reports. Make sure to include the complete stacktrace of your error when you post it there, also a bit more context about the "somewhere".

PS: My guess is on the `this` inside your `gen`, or that you forgot to `co.wrap` (or `Promise.coroutine`) your `saveAll` method so that it returns a promise.

**Comment by rafaeljesus** [comment]
Thank's @bergus I'll ask there next time :)

So I'll try what your suggestions too,

But after wrapping findAndModify(co-monk) on a try catch block I see the error comes from there and I dont know why,

Thx
