### ISSUE TITLE
No stacktrace for "a promise was created in a  handler but was not returned from it"

### ISSUE THREAD

**Issue by pocesar** [petkaantonov/bluebird#846]
I'm using bluebird as angular replacement for $q, and it's working properly. But since upgrading to 3.x I'm having the warning "a promise was created in a  handler but was not returned from it", but provided with no stacktrace, which makes it really difficult to find where the promise is not returning something from a `then` chain. How can I debug this? My browser code is kinda large (13k LOC) and uses promises extensively

**Comment by benjamingr** [comment]
This was very recently improved 2 days ago in https://github.com/petkaantonov/bluebird/releases/tag/v3.0.4 what version are you using?

**Comment by pocesar** [comment]
3.0.5

**Comment by pocesar** [comment]
it seems that it's triggering in `finally` and `done` as well (and shouldn't?)

**Comment by petkaantonov** [comment]
You should always see a stack trace for the warning no matter what, unless the environment is really hostile or something

**Comment by pocesar** [comment]
![clipboard01](https://cloud.githubusercontent.com/assets/461084/10920135/bc2604be-8255-11e5-8582-7f5ffaee3d38.png)

sometimes it does show the stack properly (long stack trace style), and it's easier to pinpoint. but the warning is giving me this code

```typescript
fbAsyncInitPromise.finally(() => {
    this.LoginState.load();
});
```

**Comment by petkaantonov** [comment]
What browser is that? Did you try Google Chrome?

Arrow functions don't have implicit return when using the form with braces, so you need to use a single-expression arrow function or return the promise

**Comment by pocesar** [comment]
Yes, in Chrome is shows. Maybe it's a Firebug limitation. 

```
Warning: a promise was created in a  handler but was not returned from it
    at Scope.$eval (http:/localhost/bower_components/angular/angular.js?v=2.0.1:15989:28)
    at $applyAsyncExpression (http://localhost/bower_components/angular/angular.js?v=2.0.1:16128:17)
    at flushApplyAsync (http://localhost/bower_components/angular/angular.js?v=2.0.1:16381:34)
    at Scope.$digest (http://localhost/bower_components/angular/angular.js?v=2.0.1:15788:11)
    at Scope.$apply (http://localhost/bower_components/angular/angular.js?v=2.0.1:16097:24)
    at http://localhost/bower_components/angular/angular.js?v=2.0.1:17864:36
```

It seems related to internals of angular that are using `then`s as sideeffects. nothing I can do about it I guess.

**Comment by petkaantonov** [comment]
If you replaced $q with bluebird then that means angular will use bluebird promises internally and you will get warnings for their mistakes.

**Comment by pocesar** [comment]
yep, makes sense. I'll have to deal with what I can in my own code, then suppress the warnings then. 
but should `finally` and `done` get warnings?

**Comment by petkaantonov** [comment]
`done` doesn't make sense but you can `return null` for now. 

If you create a promise inside finally but forgot to return it then the next handler in the chain will not wait for the promise or be able to handle its errors.

**Comment by grantila** [comment]
I'm getting these with 3.0.5 in Chrome, Firefox and Safari. "*(No stacktrace)*". Having breaked the whole application I found it to be caused by the following:

```js
		.then( function( data ) {
			if ( data !== null ) {
				authed = true;
			}
		} )
```

but got silenced by returning null:

```js
		.then( function( data ) {
			if ( data !== null ) {
				authed = true;
			}
			return null;
		} )
```

Note that the function is doing synchronous non-promise work. Nothing else. I'm not sure exactly what bluebird is trying to do, but something is absurdly fishy here. The above code is exact but extracted from a larger part of a +5MB commercial code-base that I'm not able to share here, but this bug should not be closed just yet.

**Comment by petkaantonov** [comment]
@grantila please use 3.0.6 to get full stack trace (At least in Chrome...). It cannot be caused by that function and either way  it cannot be used to reproduce the problem.

**Comment by grantila** [comment]
Can or cannot is irrelevant, as I can turn on and off that `return null;` and *every time* get the same result. It happens.
Same behavior with 3.0.6 and still no call stack.

When I break in the logger function, I see that the callstack begins with `Async.prototype.settlePromises` calling `promise._settlePromises();` and then onwards. Full Chrome stack:

```
e.9.module.exports.printWarning (bluebird.js:1401)
formatAndLogError (bluebird.js:1035)
warn (bluebird.js:931)
e.9.module.exports.Promise._warn (bluebird.js:722)
checkForgottenReturns (bluebird.js:908)
e.22.module.exports.Promise._settlePromiseFromHandler (bluebird.js:3009)
e.22.module.exports.Promise._settlePromise (bluebird.js:3054)
e.22.module.exports.Promise._settlePromise0 (bluebird.js:3099)
e.22.module.exports.Promise._settlePromises (bluebird.js:3182)
(anonymous function) (bluebird.js:162)
```

So far, I've found all other places (quite a few) in my code where I had to silence this warning (and by the way, *zero* of them were errors, but intentional side-handled promise chains), but without a call stack in a large codebase, I'm thinking of permanently just silence all bluebird warnings, or is there a way to silence only this particular one? It hasn't helped me at all, only caused head-aches. I'm sure it might help some young unexperienced newcomers, but then maybe this should be an opt-in warning instead. I personally don't think that *expecting a function that returns undefined is a programmer error* just because further down the call-chain someone created a promise, but I guess this discussion has already been handled elsewhere.

**Comment by petkaantonov** [comment]
The way to silence to an intentionally forgotten return is to return null as advised on the warning page. 

It's not possible to detect if the function itself created the promise or the function called some other function that created the promise, that's why there is a warning even if the function itself is not immediately creating a promise. Well, it is possible with arguments.caller but it doesn't work in strict mode.

Not getting any call stack with your code is a bug, most likely because I have forgotten to add a captureStackTrace() somewhere. The stack frames from inside bluebird are intentionally removed as they are not useful.

**Comment by petkaantonov** [comment]
@grantila it looks like the issue might be that the default of 10 stack frames isn't enough to capture any user frames. Can you try in chrome or node with e.g. `Error.stackTraceLimit = 25` and see if you get any trace?

**Comment by grantila** [comment]
I've refactored a lot of code which made that particular warning go away, but I can find another place where I have:
```
.finally( function( ) {
    emitter.emit( 'event', foobar );
    return null;
} )
```

where the only solution seems to be (although this *does* return null) is:

```
.finally( function( ) {
    setImmediate( _ => emitter.emit( 'event', foobar ) );
    return null;
} )
```

and then it goes away... I have to say, something is still fishy about this.

**Comment by petkaantonov** [comment]
It's because the event listeners of "event" are creating promises and events are emitted synchronously which means it's same as calling those functions directly in your handler. Return null not working inside finally or tap to ignore it is a bug.

**Comment by grantila** [comment]
Yeah, event emitters are synchronous, which is what makes this painful to debug.
Simplified, this does the same for me:

```js
.finally( function( ) {
    Promise.resolve( "foobar" );
    return null; // <-- as you say, this is ignored.
} )
```

The path up to the above is huge and filled with a bunch of Promise.resolve() and Promise.try() (if that will help), and simply isolating this doesn't reproduce it, but it's obviously a bug.

**Comment by grantila** [comment]
Fantastic 👏
