### ISSUE TITLE
Arguments against `.done()`?

### ISSUE THREAD

**Issue by gabmontes** [petkaantonov/bluebird#879]
@petkaantonov or anyone can please lead me to any discussion with arguments against using `.done()`? The statement "The use of this method is heavily discouraged" at https://github.com/petkaantonov/bluebird/blame/master/docs/docs/api/done.md#L20 is very strong and am looking for more information about it (GitHib issues, blog posts, videos, etc).

Thanks in advance!

**Comment by stefanpenner** [comment]
A relevant discussion -> https://github.com/domenic/promises-unwrapping/issues/19

**Comment by petkaantonov** [comment]
You can use `.catch(thrower)` in place of done for error handling but both have the same problem that you need to remember to use it everywhere and it's in practice not so easy to make sure every chain always has a done. 

Perhaps coincidence but [someone again just commented](https://github.com/petkaantonov/bluebird/issues/493#issuecomment-158459154) on an issue how confusing it was to see a unhandled rejection when they thought they had all chains covered with a handler when they did not. Imagine with a .done when there is nothing to even warn you about that one of the chains was covered (presumably if you are using .done you would turn unhandled rejections off).

**Comment by gabmontes** [comment]
Thanks for the quick responses! I guess the discussion will keep going for a while. Thanks again!!

**Comment by georgir** [comment]
> Perhaps coincidence but someone again just commented on an issue how confusing it was to see a unhandled rejection when they thought they had all chains covered with a handler when they did not. Imagine with a .done when there is nothing to even warn you about that one of the chains was covered (presumably if you are using .done you would turn unhandled rejections off).

Well, to me it sometimes seems the other way around. People get confused with the automatic unhandled rejection detection, because they are unaware of some dangling side-chains they accidentally created. If they are allowed to monitor only the main chain for unhandled rejections by specifying it explicitly, it may be better. They probably do not care for exceptions in minor side chains, and many of those are even so simple (after their branch-off point) that they can not fail in principle. But now an error in earlier common parts of the promise chain still reaches those side-chains and gets logged as unhandled, while it is perfectly handled on the main chain.
